Added patch for exec_and_log in sh/scripts_common.sh to log command output along with predefined error message.

diff --git a/opennebula/tar/src/main/patches/tm-compressed-images-and-no-world-rw.patch b/opennebula/tar/src/main/patches/tm-compressed-images-and-no-world-rw.patch
--- a/opennebula/tar/src/main/patches/tm-compressed-images-and-no-world-rw.patch
+++ b/opennebula/tar/src/main/patches/tm-compressed-images-and-no-world-rw.patch
@@ -30,7 +30,7 @@ index ea98602..3f68e83 100755
 +exec_and_log "ssh $DST_HOST chmod ug+w,o-rwx $DST_PATH"
  
 diff --git a/src/mad/sh/scripts_common.sh b/src/mad/sh/scripts_common.sh
-index 3d59047..6ac998e 100755
+index 2af7a31..1018022 100755
 --- a/src/mad/sh/scripts_common.sh
 +++ b/src/mad/sh/scripts_common.sh
 @@ -32,6 +32,9 @@ SED=/bin/sed
@@ -43,7 +43,46 @@ index 3d59047..6ac998e 100755
  
  # Used for log messages
  SCRIPT_NAME=`basename $0`
-@@ -145,3 +148,19 @@ function timeout_exec_and_log
+@@ -88,24 +91,31 @@ function error_message
+ # the command fails
+ function exec_and_log
+ {
++    # If set to 'true' '$message' will be merged with '$output'
++    mergeoutput=$3
+     message=$2
+-    output=`$1 2>&1 1>/dev/null`
++    output=`$1 2>&1`
+     code=$?
+     if [ "x$code" != "x0" ]; then
+         log_error "Command \"$1\" failed."
+         log_error "$output"
+-        if [ -z "$message" ]; then
+-            error_message "$output"
+-        else
+-            error_message "$message"
+-        fi
++        case $# in
++            2 )
++               error_message "$message"
++               ;;
++            3 )
++               [ "$mergeoutput" = "true" ] && error_message "$message\n$output"
++               ;;
++            * )
++               error_message "$output"
++               ;;
++        esac
+         exit $code
+     fi
+     log "Executed \"$1\"."
+ }
+ 
+ 
+-
+ # Like exec_and_log but the first argument is the number of seconds
+ # before here is timeout and kills the command
+ #
+@@ -145,3 +155,19 @@ function timeout_exec_and_log
          exit $CMD_CODE
      fi
  }
